modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/auioc/clientesh-mcmod/issues"

[[mods]]
modId="clientesh"
version="${file.jarVersion}"
updateJSONURL="https://hi.auioc.org/clientesh-mcmod/update/1.18.2.json"
displayName="ClientEsh"
displayURL="http://hi.auioc.org/clientesh-mcmod/"
credits="AUIOC"
authors="WakelssSloth56"
description='''
'''

[[dependencies.clientesh]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clientesh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clientesh]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.6.7,)"
    ordering="NONE"
    side="BOTH"
